name: 'Conditional value'
description: 'Conditional value'
author: 'krb70'
inputs:
  cond:
    description: 'condition. [true,false]'
    required: true
  if_true:
    description: 'output value if cond is true'
    default: ''
  if_false:
    description: 'output value if cond is false'
    default: ''
outputs:
  value:
    description: 'output value'
    value: ${{ steps.result.outputs.value }}
runs:
  using: composite
  steps:
    - shell: python 
      id: result 
      env:
        COND: ${{ inputs.cond }}
        IFTRUE: ${{ inputs.if_true }}
        IFFALSE: ${{ inputs.if_false }}
      run: |
          import os, uuid
          e = os.environ
          val = (e['IFTRUE'] if e['COND'].lower()[0] == 't' else e['IFFALSE'])
          delim = 'delim_' + uuid.uuid4().hex
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"""value<<{delim}\n{val}\n{delim}\n""")
