
name: pyshell
on: [push]
jobs:
    build:
        name: py shell
        runs-on: [ubuntu-latest]
        env:
            REF_NAME: ${{ github.ref_name }}
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: A
              id: abc
              uses: krb70/pyshellaction/cond@v1
              with:
                cond: ${{ github.ref_name == 'main' || github.ref_name == 'refs/heads/main' }}
                if_true: |
                  Long
                  multiline string
                  to return
                if_false: |
                  Another
                  multiline string
                  to set 
            - name: C
              id: c
              shell: python
              run: |
                 import subprocess
                 import os, sys, shlex
                 print("${{ github.ref_name }}")
                 print("""${{ steps.abc.outputs.value }}""")
                 print(sys.version)
                 subprocess.check_call(shlex.split("pwd"))

